import re
import textwrap
from datetime import datetime

def _safe_id(name: str, prefix: str = "x") -> str:
    """Создает 100% валидный Ren'Py идентификатор (начинается с буквы, только ASCII)"""
    if not name or not str(name).strip():
        return f"{prefix}_default"
    safe = re.sub(r'[^a-zA-Z0-9_]', '_', str(name))
    safe = safe.strip('_')
    if not safe: return f"{prefix}_default"
    if safe[0].isdigit(): safe = '_' + safe
    if not safe[0].isalpha(): safe = f"{prefix}_{safe}"
    return safe

class CodeGenerator:
    def __init__(self, characters: dict, labels: dict):
        self.characters = characters
        self.labels_data = labels
        self._images = set()
        self._music = {}
        self._sounds = {}

    def generate_full_script(self) -> str:
        self._collect_assets()
        parts = [
            self._header(),
            self._characters(),
            self._images_def(),
            self._audio_def(),
            self._labels()
        ]
        script = "\n\n".join(p for p in parts if p)
        return script.rstrip() + "\n"

    def _collect_assets(self):
        for blocks in self.labels_data.values():
            for block in blocks:
                p = block.get("properties", {})
                t = block.get("type")
                if t == "Задний фон" and p.get("bg_name"):
                    name = p["bg_name"].strip()
                    self._images.add((name, f"images/backgrounds/{name}"))
                elif t == "Музыка" and p.get("name"):
                    name = p["name"].strip()
                    self._music[_safe_id(name, "m")] = f"audio/music/{name}"
                elif t == "Звук" and p.get("name"):
                    name = p["name"].strip()
                    self._sounds[_safe_id(name, "s")] = f"audio/sound/{name}"
                elif t == "Спрайт" and p.get("sprite_name"):
                    name = p["sprite_name"].strip()
                    if name:
                        safe_name = _safe_id(name.rsplit('.', 1)[0])
                        char = p.get("character", "").strip()
                        if char and char != "Мысли":
                            path = f"images/characters/{char}/{name}"
                        else:
                            path = f"images/characters/{name}"
                        self._images.add((safe_name, path))

    def _header(self):
        return f"# Auto-generated by VN Maker\n# {datetime.now()}"

    def _characters(self):
        lines = []
        for name, data in self.characters.items():
            var = _safe_id(name, "char")
            color = data.get("color", "#ffffff")
            lines.append(f'define {var} = Character(_("{name}"), color="{color}")')
        return "\n".join(lines)

    def _images_def(self):
        lines = []
        for name, path in sorted(self._images):
            var = _safe_id(name, "img")
            lines.append(f'image {var} = "{path}"')
        return "\n".join(lines)

    def _audio_def(self):
        lines = []
        for var, path in sorted(self._music.items()):
            lines.append(f'define audio.{var} = "{path}"')
        for var, path in sorted(self._sounds.items()):
            lines.append(f'define audio.{var} = "{path}"')
        return "\n".join(lines)

    def _labels(self):
        parts = []
        for lbl, blocks in self.labels_data.items():
            safe_lbl = _safe_id(lbl, "label")
            sorted_b = sorted(blocks, key=lambda b: b.get("y", 0))
            code = [f"label {safe_lbl}:"]
            for b in sorted_b:
                code.append(f"    {self._block_code(b)}")
            code.append("    return")
            parts.append("\n".join(code))
        return "\n\n".join(parts)

    def _block_code(self, block: dict) -> str:
        t = block.get("type")
        p = block.get("properties", {})
        def gs(k, d=""): return str(p.get(k, d)).strip()

        if t == "Текст":
            char = gs("character")
            txt = gs("text")
            if not txt: return "# Пустой текст"
            var = _safe_id(char, "char") if char else None
            return f'{var} "{txt}"' if var else f'"{txt}"'

        elif t == "Спрайт":
            sprite = gs("sprite_name")
            if not sprite: return "# Нет спрайта"
            
            img = _safe_id(sprite.rsplit('.', 1)[0], "img")
            action = gs("action", "show")
            pos = gs("position", "center")
            xalign = p.get("xalign", 0.5)
            yalign = p.get("yalign", 1.0)
            zoom = p.get("zoom", 1.0)
            transition = gs("transition", "dissolve")
            trans_cmd = f" with {transition}" if transition != "None" else ""

            if action == "hide":
                return f"hide {img}{trans_cmd}"

            pos_map = {
                "left": "at left",
                "right": "at right", 
                "truecenter": "at truecenter",
                "center": ""
            }
            
            needs_transform = (pos == "custom") or (zoom != 1.0)
            
            if not needs_transform and zoom != 1.0:
                needs_transform = True
            
            if needs_transform:
                lines = [f"{action} {img}:"]
                
                if pos == "custom":
                    lines.append(f"    xalign {xalign}")
                    lines.append(f"    yalign {yalign}")
                elif pos in pos_map and pos_map[pos]:
                    if pos == "left":
                        lines.append(f"    xalign 0.0")
                    elif pos == "right":
                        lines.append(f"    xalign 1.0")
                    elif pos == "truecenter":
                        lines.append(f"    xalign 0.5")
                        lines.append(f"    yalign 0.5")
                
                if zoom != 1.0:
                    lines.append(f"    zoom {zoom}")
                
                code = "\n    ".join(lines)
                if trans_cmd:
                    code += f"\n    {trans_cmd.strip()}"
                return code
            else:
                pos_cmd = pos_map.get(pos, "")
                return f"{action} {img} {pos_cmd}{trans_cmd}".strip()

        elif t == "Задний фон":
            bg = gs("bg_name")
            if not bg: return "# Нет фона"
            
            transition = p.get("transition", "fade")
            clear_layer = p.get("clear_layer", True)
            
            cmd = "scene" if clear_layer else "show bg"
            
            trans_str = f" with {transition}" if transition and transition != "None" else ""
            
            return f"{cmd} {_safe_id(bg, 'img')}{trans_str}"

        elif t == "Музыка":
            name = gs("name")
            if not name: return "# Нет музыки"
            var = _safe_id(name, "m")
            act = gs("action", "play")
            
            if act == "stop":
                return "stop music"
            
            params = []
            
            vol = p.get("volume", 1.0)
            try:
                vol = float(vol)
                if vol != 1.0:
                    params.append(f"volume {vol}")
            except: pass

            fadein = p.get("fadein", 0)
            try:
                fadein = float(fadein)
                if fadein > 0:
                    params.append(f"fadein {fadein}")
            except: pass

            if p.get("loop", False):
                params.append("loop")
                
            params_str = " " + " ".join(params) if params else ""
            return f"play music {var}{params_str}"

        elif t == "Звук":
            name = gs("name")
            if not name: return "# Нет звука"
            var = _safe_id(name, "s")
            act = gs("action", "play")
            
            if act == "stop":
                return "stop sound"
            
            params = []
            
            vol = p.get("volume", 1.0)
            try:
                vol = float(vol)
                if vol != 1.0:
                    params.append(f"volume {vol}")
            except: pass

            params_str = " " + " ".join(params) if params else ""
            return f"play sound {var}{params_str}"

        elif t == "Выбор ответа":
            choices = p.get("choices", [])
            if not choices: return "# Пустой выбор"
            lines = ["menu:"]
            for c in choices:
                txt = c.get("text", "Вариант").strip()
                tgt = _safe_id(c.get("target", "start"), "label")
                cond = c.get("condition", "").strip()
                if cond:
                    lines.append(f'    "{txt}" if {cond}:')
                else:
                    lines.append(f'    "{txt}":')
                lines.append(f'        jump {tgt}')
            return "\n    ".join(lines)
        
        elif t == "Анимация спрайта":
            sprite = p.get("sprite_name", "").strip()
            duration = p.get("duration", 1.0)
            start_x = p.get("start_x", 0.2)
            end_x = p.get("end_x", 0.8)
            anim_type = p.get("anim_type", "move")
            easing = p.get("easing", "linear")
            
            if not sprite:
                return "# Нет спрайта для анимации"
            
            img = _safe_id(sprite.rsplit('.', 1)[0], "img")
            
            anim_map = {
                "move": "xalign",
                "ease": "xalign",
                "linear": "xalign",
                "zoom": "zoom"
            }
            
            easing_map = {
                "linear": "linear",
                "easein": "easein",
                "easeout": "easeout",
                "easeinout": "easeinout"
            }
            renpy_easing = easing_map.get(easing, "linear")
            
            target_attr = anim_map.get(anim_type, "xalign")
            if target_attr == "zoom":
                target_value = 1.5  
            else:
                target_value = end_x
            
            lines = [
                f"show {img}:",
                f"    {renpy_easing} {duration} {target_attr} {target_value}"
            ]
            
            return "\n    ".join(lines)